package com.automation.common.bdd.stepdefs;

import com.automation.common.api.domainObjects.SoapGetHolidayDateDO;
import com.taf.automation.bdd.TestNGCucumberBase;
import cucumber.api.java.en.Given;
import cucumber.api.java.en.Then;
import cucumber.api.java.en.When;

/**
 * Class to hold the Soap Holiday Step Definitions specifically<BR>
 * <B>Notes: </B>
 * <OL>
 * <LI>The template methods were generated by using IntelliJ from holiday.feature</LI>
 * <LI>The Given lines of code must be unique across all step def files or an error will occur (no features.)</LI>
 * </OL>
 */
public class SoapHolidayStepDefs extends TestNGCucumberBase {
    private SoapGetHolidayDateDO getHolidayDateDO;

    @Given("^Using the dataSet from the \"([^\"]*)\" file for the Soap Holiday Test$")
    public void using_the_dataSet_from_the_file_for_the_Soap_Holiday_Test(String dataSet) {
        getHolidayDateDO = new SoapGetHolidayDateDO().fromResource(dataSet);
    }

    @When("^I send the request$")
    public void i_send_the_request() {
        getHolidayDateDO.sendRequest();
    }

    @Then("^I receive the proper status and response$")
    public void i_receive_the_proper_status_and_response() {
        getHolidayDateDO.validateStatus();
        getHolidayDateDO.validateResponse();
    }

}
